from flask import Flask, render_template
import random

app = Flask(__name__)

fun_facts = [
    "Blæksprutter har tre hjerter.",
    "Bananer er bær, men jordbær er det ikke.",
    "Python er opkaldt efter Monty Python – ikke slangen!",
    "Jorden er ikke helt rund – den er lidt flad ved polerne.",
    "Et lyn er varmere end overfladen på solen.",
    "Honning aldrig beder - det kan holde sig i tusinder af år!",
    "Kvækfroer kan ikke spytte - de sluger deres bytte hele.",
    "En snylteflue kan flyve baglæns.",
    "Giraffer har samme antal nakkehvirvler som mennesker.",
    "En pingvin kan hoppe op til 2 meter højt.",
    "Krokodiller kan ikke ryste hovedet fra side til side.",
    "En elefant kan ikke hoppe - overhovedet!",
    "Kangarooer kan ikke gå baglæns.",
    "En blåhval kan spise op til 4 tons krill om dagen.",
    "Hajer har ikke knogler - kun brusk.",
    "En kolibri kan flyve baglæns og på tværs.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan gå op ad trapper, men ikke ned.",
    "Hjorte kan ikke hoste.",
   "En mus kan ikke brække sig.",
    "Krokodiller kan ikke rynke panden.",
    "En elefant er det eneste pattedyr der ikke kan hoppe.",
    "Giraffer har sorte tunger.",
    "En pingvin kan ikke flyve, men kan svømme 25 km/t.",
    "Kvækfroer har ingen tænder.",
    "En blåhval er så stor, at et menneske kan svømme gennem dens årer.",
    "Hajer har ikke skæl - de har hud som sandpapir.",
    "En kolibri kan slå vingerne 80 gange i sekundet.",
    "Kameleoner kan ændre farve på under et minut.",
    "En orm har ingen øjne eller ører.",
    "Delfiner har navne og kalder hinanden ved navn.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
     "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
     "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
    "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se i to retninger på samme tid.",
    "En orm kan ikke hoste eller nys.",
    "Delfiner sover med et øje åbent.",
    "En ko kan producere 200 liter spyt om dagen.",
    "Hjorte kan løbe 50 km/t.",
    "En mus kan overleve fald på 3 meter uden skade.",
    "Krokodiller kan ikke røre tungen.",
    "En elefant kan huske ting i 20 år.",
    "Giraffer sover kun 2 timer om dagen.",
    "En pingvin kan dykke 500 meter dybt.",
    "Kvækfroer kan ikke spytte eller brække sig.",
    "En blåhval kan blive 100 år gammel.",
     "Hajer har 5-15 rækker af tænder.",
    "En kolibri kan flyve op og ned uden at bevæge hovedet.",
    "Kameleoner kan se 360 grader rundt.",
    "En orm kan ikke lukke øjnene - de har ingen øjenlåg.",
    "Delfiner kan genkende sig selv i et spejl.",
    "En ko har fire maver.",
    "Hjorte kan høre lyde på 2 km afstand.",
    "En mus kan klemme sig gennem et hul på størrelse med en blyant.",
    "Krokodiller kan ikke svede.",
    "En elefant kan høre lyde på 10 km afstand.",
    "Giraffer har ingen stemmebånd.",
    "En pingvin kan holde vejret i 20 minutter.",
    "Kvækfroer kan ikke lukke øjnene - de har ingen øjenlåg.",
    "En blåhval kan spytte vand 9 meter op i luften.",
    "Hajer kan lugte en dråbe blod i 100 liter vand."
]

@app.route('/')
def show_funfact():
    fact = random.choice(fun_facts)
    return render_template('index.html', funfact=fact)

if __name__ == '__main__':
    app.run(debug=True)
